default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5
  min_messages: WARNING
  username: ibms
  password: ibms

development:
  <<: *default
  database: sample_dev

test:
  <<: *default
  database: sample_test
